---

- name: Ensure usbmon system group is present
  group:
    name: 'usbmon'
    state: 'present'
    system: True

- name: Setup udev rule for usbmon
  template:
    src: 'etc/udev/rules.d/usbmon.rules.j2'
    dest: '/etc/udev/rules.d/99-usbmon.rules'
